services:
  web:
    build:
      context: ./
    image: ghcr.io/ramadhanamizudin/lekir:main
    volumes:
      - ./:/var/www/html
    ports:
      - "8899:80"
    depends_on:
      - db
  db:
    image: mysql:8.0
    volumes:
      - ./lekir.sql:/docker-entrypoint-initdb.d/lekir.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lekir
